name: CI

on:
  push:
    branches: ["prueba"]
  pull_request:
    branches: ["prueba"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          

      - name: Create virtualenv, install, lint, test, deploy
        run: |
          # Crear un entorno virtual en la carpeta "venv"
          python -m venv venv
          # Activarlo
          source venv/bin/activate
          
          # Instalar dependencias
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Formatear con autopep8
          autopep8 --in-place --recursive --aggressive --aggressive .
          
          # Lint con flake8 (excluyendo la carpeta venv)
          flake8 --exclude=venv .
          
          # Tests con pytest
          pytest --maxfail=1 --disable-warnings -q
          
          # Finalmente, desplegar con Zappa
          zappa deploy download-dev
          zappa deploy upload-dev
